--ALBUM--
CREATE TABLE ALBUM(
	ID NUMBER NOT NULL,
	TITULO VARCHAR2(25),
    IMG NVARCHAR2(50),
	PRIMARY KEY (ID)
);
--GENERO--
CREATE TABLE GENERO(
	ID NUMBER NOT NULL,
	NOMBRE VARCHAR2(25),
    IMG NVARCHAR2(50),
	PRIMARY KEY (ID)
);
--ARTISTA--
CREATE TABLE ARTISTA(
	ID NUMBER NOT NULL,
	NOMBRE VARCHAR2(25),
    IMG NVARCHAR2(50),
	PRIMARY KEY (ID)
);

--CANCION--
CREATE TABLE CANCION(
	ID NUMBER NOT NULL,
	TITULO VARCHAR2(50),
    DURACION NUMBER,
    URL VARCHAR2(25),
    ALBUM NUMBER,
    GENERO NUMBER,
	PRIMARY KEY (ID)
);
--CANCION_ARTISTA--
CREATE TABLE CANCION_ARTISTA(
    IDCANCION NUMBER NOT NULL,
    IDARTISTA NUMBER NOT NULL,
    PRIMARY KEY (IDCANCION,IDARTISTA)
);

--LLAVES FORANEAS--
ALTER TABLE CANCION ADD(
    FOREIGN KEY(ALBUM) REFERENCES ALBUM(ID),
    FOREIGN KEY(GENERO) REFERENCES GENERO(ID)
);

ALTER TABLE CANCION_ARTISTA ADD(
    FOREIGN KEY(IDCANCION) REFERENCES CANCION(ID),
    FOREIGN KEY(IDARTISTA) REFERENCES ARTISTA(ID)
);